/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
    alias(libs.plugins.kotlin.jvm)
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api(libs.com.github.briandilley.jsonrpc4j.jsonrpc4j)
    api(libs.com.fasterxml.jackson.module.jackson.module.kotlin)
    api(libs.com.fasterxml.jackson.core.jackson.databind)
    api(libs.com.neovisionaries.nv.websocket.client)
    api(libs.kotlin.stdlib)
    api(libs.kotlin.reflect)
    api(libs.org.bitcoinj.bitcoinj.core)
    api(libs.io.reactivex.rxjava2.rxjava)

}

group = "com.github.jleskovar"
version = "1.2.4"
description = "btc-rpc-client"
java.sourceCompatibility = JavaVersion.VERSION_1_8
kotlin {
    jvmToolchain {
        languageVersion.set(JavaLanguageVersion.of(8))
    }
}
publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
